version: '3.8'

services:
  chatbot:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    # Enable hot reload for development
    command: chainlit run main.py --host 0.0.0.0 --port 7860 --watch 