apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-test-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapr-test-app
  template:
    metadata:
      labels:
        app: dapr-test-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dapr-test-app"
        dapr.io/app-port: "80"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
      - name: app
        image: nginx:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dapr-test-app
  namespace: default
spec:
  selector:
    app: dapr-test-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
