# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"/\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"+\n\x0fGetUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\"\x12\n\x10ListUsersRequest\".\n\x11ListUsersResponse\x12\x19\n\x05users\x18\x01 \x03(\x0b\x32\n.user.User2\x83\x01\n\x0bUserService\x12\x36\n\x07GetUser\x12\x14.user.GetUserRequest\x1a\x15.user.GetUserResponse\x12<\n\tListUsers\x12\x16.user.ListUsersRequest\x1a\x17.user.ListUsersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=20
  _globals['_USER']._serialized_end=67
  _globals['_GETUSERREQUEST']._serialized_start=69
  _globals['_GETUSERREQUEST']._serialized_end=97
  _globals['_GETUSERRESPONSE']._serialized_start=99
  _globals['_GETUSERRESPONSE']._serialized_end=142
  _globals['_LISTUSERSREQUEST']._serialized_start=144
  _globals['_LISTUSERSREQUEST']._serialized_end=162
  _globals['_LISTUSERSRESPONSE']._serialized_start=164
  _globals['_LISTUSERSRESPONSE']._serialized_end=210
  _globals['_USERSERVICE']._serialized_start=213
  _globals['_USERSERVICE']._serialized_end=344
# @@protoc_insertion_point(module_scope)
